name: Check

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore state
        uses: actions/cache@v3
        with:
          path: last_count.txt
          key: rebo-state-${{ github.run_id }}
          restore-keys: rebo-state-

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Set webhook secret
        run: echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - run: python script.py

      - name: Save state
        uses: actions/cache@v3
        with:
          path: last_count.txt
          key: rebo-state-${{ github.run_id }}
