name: Check

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # STATE BESTAND RESTOREN (laatste telling)
      - name: Restore state
        uses: actions/cache@v3
        with:
          path: last_count.txt
          key: rebo-state
          restore-keys: rebo-state

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      # Secret in ENV zetten
      - name: Set webhook env
        run: echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run script
        run: python script.py

      # STATE OPNIEUW OPSLAAN
      - name: Save state
        uses: actions/cache@v3
        with:
          path: last_count.txt
          key: rebo-state
